### ISSUE TITLE
How to install splitp in command line?

### ISSUE THREAD

**Issue by vivianschu** [COMBINE-lab/splitp#1]
Would be really helpful if there were some instructions for installation.

**Comment by chanalim** [comment]
Hello, 

I had to figure out this myself as well, but you just need to git clone the repository or download a zip folder from it then follow the link here for building the Rust package since the code were written in (.rs) files : https://jfrog.com/knowledge-base/how-to-build-and-manage-rust-packages-with-cargo/

Once you build the package you can just use this command: 
target/release/splitp --read-file <READ_FILE> --bc-map <BC_MAP> --start <START> --end <END>

**Comment by rob-p** [comment]
Thanks @chanalim!  Yes, I should add a brief section to the README about this.
